version: '3.9'
services:
  api_service:
    environment:
      MONGO_USERNAME: 'root'
      MONGO_PASSWORD: 'rootpassword'
      MONGO_DATABASE: 'admin'
    build: .
    restart: always
    depends_on:
      - mongo_db
    ports:
      - "8080:8080"
  mongo_db:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - "27017:27017"
    volumes:
      - "$PWD/mongo-entrypoint/:/docker-entrypoint-initdb.d/"
    command: mongod
