apiVersion: apps/v1
kind: Deployment
metadata:
  name: coinbank
  labels:
    app: coinbank
spec:
  replicas: 1
  selector:
    matchLabels:
      app: coinbank
  template:
    metadata:
      labels:
        app: coinbank
    spec:
      containers:
        - name: coinbank
          image: samirjha123/coinbank:0.0.4-SNAPSHOT-2
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: mongodb
                  key: database-name
            - name: MONGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-user
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb
                  key: database-password
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb
  labels:
    app: mongodb
spec:
  ports:
    - port: 27017
      protocol: TCP
  selector:
    app: mongodb
---
apiVersion: v1
kind: Service
metadata:
  name: coinbank
  labels:
    app: coinbank
    spring-boot: "true"
spec:
  ports:
    - name: http-api
      port: 8080
      protocol: TCP
  selector:
    app: coinbank
  sessionAffinity: None
  type: ClusterIP
